import { BarChart3, FileStack, Menu, MessageSquare, PanelLeftClose, X } from "lucide-react";
import { useState } from "react";
import { NavLink, Outlet } from "react-router-dom";

import { useApp } from "../context/AppContext.jsx";
import Sidebar from "./Sidebar.jsx";

const tabLinkClasses = ({ isActive }) => `flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold transition ${isActive ? "bg-white text-brand-700 shadow-sm" : "text-slate-500 hover:bg-white/60 hover:text-slate-800"}`;

export default function Layout() {
  const { setup, documents } = useApp();
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  return <div className="app-shell flex w-full overflow-hidden bg-[#f7f8fc]">
    <aside className={`relative hidden shrink-0 transition-all duration-300 md:block ${sidebarCollapsed ? "w-0 overflow-hidden" : "w-80"}`}><Sidebar /><button onClick={() => setSidebarCollapsed(true)} className="absolute -right-3 top-7 z-10 flex h-6 w-6 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-500 shadow-sm" aria-label="Collapse sidebar"><PanelLeftClose size={14} /></button></aside>
    {sidebarCollapsed && <button onClick={() => setSidebarCollapsed(false)} className="absolute left-4 top-5 z-20 hidden h-9 w-9 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 shadow-sm md:flex" aria-label="Open sidebar"><Menu size={18} /></button>}
    {sidebarOpen && <div className="fixed inset-0 z-50 md:hidden"><button className="absolute inset-0 bg-slate-950/35" onClick={() => setSidebarOpen(false)} aria-label="Close document panel" /><aside className="thin-scrollbar relative h-full w-[min(88vw,340px)] overflow-y-auto bg-white shadow-2xl"><button onClick={() => setSidebarOpen(false)} className="absolute right-4 top-4 z-10 rounded-lg p-1.5 text-slate-500 hover:bg-slate-100" aria-label="Close document panel"><X size={18} /></button><Sidebar /></aside></div>}
    <div className="flex min-w-0 flex-1 flex-col"><header className="border-b border-slate-200/80 bg-white/90 px-4 py-3 backdrop-blur sm:px-6"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><button onClick={() => setSidebarOpen(true)} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-slate-200 text-slate-600 md:hidden" aria-label="Open document panel"><Menu size={19} /></button><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-brand-600 to-cyan-500 text-white shadow-md shadow-brand-200"><FileStack size={20} /></div><div><h1 className="text-lg font-bold tracking-tight text-slate-900 sm:text-xl">DocumentIQ</h1><p className="hidden text-xs text-slate-500 sm:block">Intelligent conversations with your PDFs</p></div></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs font-medium text-slate-600 sm:flex"><span className={`h-2 w-2 rounded-full ${setup.ready ? "bg-emerald-500" : "bg-amber-400"}`} />{setup.ready ? "System ready" : "Setup required"}</div><div className="rounded-full bg-brand-50 px-3 py-1.5 text-xs font-semibold text-brand-700">{documents.length} {documents.length === 1 ? "PDF" : "PDFs"}</div></div></div>{setup.ready && <nav className="mx-auto mt-3 flex max-w-7xl gap-1 rounded-xl bg-slate-100 p-1.5 sm:inline-flex"><NavLink to="/chat" className={tabLinkClasses}><MessageSquare size={15} /> Chat</NavLink><NavLink to="/dashboard" className={tabLinkClasses}><BarChart3 size={15} /> Library</NavLink></nav>}</header><main className="thin-scrollbar min-h-0 flex-1 overflow-y-auto">{!setup.loading && !setup.ready ? <div className="mx-auto max-w-2xl px-6 py-16"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-900 shadow-sm"><p className="font-bold">Connect your AI provider to get started</p><p className="mt-2 leading-6">Add your Gemini API key to the project’s <code>.env</code> file, then refresh this page.</p></div></div> : <Outlet />}</main><footer className="border-t border-slate-200/70 bg-white px-4 py-2 text-center text-[11px] text-slate-400">DocumentIQ · Private PDF intelligence workspace · v{setup.version || "—"}</footer></div>
  </div>;
}
