import { ArrowUp, Bot, FileSearch, Loader2, MessageSquareText, Sparkles } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import ChatMessage from "../components/ChatMessage.jsx";
import { useApp } from "../context/AppContext.jsx";
const starterQuestions = ["Summarize the key points in these documents", "What are the most important findings?", "Create a concise study guide from the PDFs", "What questions should I ask about this material?"];

export default function ChatPage() {
  const { documents, messages, chatBusy, askQuestion, hasDocuments } = useApp(); const [input, setInput] = useState(""); const textareaRef = useRef(null); const bottomRef = useRef(null);
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, chatBusy]);
  useEffect(() => { const textarea = textareaRef.current; if (!textarea) return; textarea.style.height = "auto"; textarea.style.height = `${Math.min(textarea.scrollHeight, 144)}px`; }, [input]);
  const submit = (value = input) => { const question = value.trim(); if (!question || chatBusy || !hasDocuments) return; setInput(""); askQuestion(question); };
  return <div className="mx-auto flex h-full w-full max-w-6xl flex-col px-4 py-5 sm:px-6 lg:px-8">
    <div className="mb-4 flex shrink-0 flex-wrap items-center justify-between gap-3">
      <div><p className="eyebrow">Knowledge workspace</p><h2 className="mt-1 text-xl font-bold tracking-tight text-slate-900">Ask your documents</h2></div>
      <div className="flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-600 shadow-sm"><FileSearch size={14} className="text-brand-600" />{documents.length} {documents.length === 1 ? "document" : "documents"} available</div>
    </div>
    <section className="thin-scrollbar relative min-h-0 flex-1 overflow-y-auto overscroll-contain">
      {messages.length === 0 ? <div className="flex min-h-full items-center justify-center pb-6"><div className="w-full max-w-3xl text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-brand-600 to-cyan-500 text-white shadow-lg shadow-brand-200"><Sparkles size={28} /></div><h3 className="mt-5 text-2xl font-bold tracking-tight text-slate-900">{hasDocuments ? "Ready when you are" : "Build your knowledge base"}</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">{hasDocuments ? "Ask a question and get a focused answer grounded in your indexed PDFs, complete with source pages." : "Upload and process one or more PDFs from the Documents panel. Your files will be indexed locally and ready to query."}</p>{hasDocuments && <div className="mt-7 grid gap-3 text-left sm:grid-cols-2">{starterQuestions.map((question) => <button key={question} onClick={() => submit(question)} className="flex items-start gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-left text-sm text-slate-600 shadow-sm transition hover:-translate-y-0.5 hover:border-brand-200 hover:shadow-md"><MessageSquareText size={17} className="mt-0.5 shrink-0 text-brand-600" /><span>{question}</span></button>)}</div>}</div></div> : <div className="space-y-5 pb-4">{messages.map((message, index) => <ChatMessage key={`${message.role}-${index}`} message={message} />)}{chatBusy && <div className="flex items-start gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-brand-600 text-white shadow-sm"><Bot size={16} /></div><div className="flex items-center gap-2 rounded-2xl rounded-tl-md border border-slate-200 bg-white px-4 py-3 text-sm text-slate-500 shadow-sm"><Loader2 size={15} className="animate-spin text-brand-600" /> Searching your knowledge base…</div></div>}<div ref={bottomRef} /></div>}
    </section>
    <form onSubmit={(event) => { event.preventDefault(); submit(); }} className="mt-3 shrink-0 pt-1">
      <div className="rounded-2xl border border-slate-200 bg-white p-2 shadow-lg shadow-slate-200/60 transition focus-within:border-brand-300 focus-within:ring-4 focus-within:ring-brand-100/70"><div className="flex items-end gap-2"><textarea ref={textareaRef} value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); submit(); } }} rows={1} disabled={!hasDocuments || chatBusy} placeholder={hasDocuments ? "Ask anything about your PDFs…" : "Upload a PDF to start a conversation"} className="max-h-36 min-h-[44px] flex-1 resize-none bg-transparent px-3 py-2.5 text-sm text-slate-800 outline-none placeholder:text-slate-400 disabled:cursor-not-allowed" /><button type="submit" disabled={chatBusy || !input.trim() || !hasDocuments} aria-label="Send question" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-brand-600 text-white shadow-sm transition hover:bg-brand-700 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-400">{chatBusy ? <Loader2 size={18} className="animate-spin" /> : <ArrowUp size={19} />}</button></div><div className="flex items-center justify-between px-3 pb-1 pt-1 text-[11px] text-slate-400"><span>Answers are generated from your indexed documents.</span><span className="hidden sm:inline">Enter to send · Shift + Enter for a new line</span></div></div>
    </form>
  </div>;
}
